name: "Infra: PR block merge"
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  block_merge:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # https://github.com/mheap/github-action-required-labels/releases/tag/5.6.0
        with:
          mode: exactly
          count: 0
          labels: >
            status/blocked,
            status/needs-attention,
            status/on-hold,
            status/pending,
            status/triage,
            status/pending-backend,
            status/pending-frontend,
            status/pending-QA
